server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dronesdb
    username: postgres
    password: Admin
    hikari:
      maximum-pool-size: 10
  jackson:
    serialization:
      write-dates-as-timestamps: false   # (kebab-case est√°ndar)

app:
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://localhost:5174"
      - "http://localhost:8080"

app.jwt:
  secret: "super-secreto-demostracion-pon-algo-mas-largo-porfa-1234567890"
  ttl-minutes: 120
